<a href="https://colab.research.google.com/github/ilhamsyamsuddin/intermediate-python-batch4/blob/main/Pert2_Numpy_(copy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Adding, removing, and sorting elements

In [ ]:
import numpy as np

In [ ]:
dtype = [('name', 'U10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)
a

array([('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)],
      dtype=[('name', '<U10'), ('height', '<f8'), ('age', '<i8')])

In [ ]:
# Append

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.append(arr, (10,11,12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

When axis is specified, values must have the correct shape.

In [ ]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.append(arr1, [[10,11,12]], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
#Concatenate arrays

In [ ]:
a = np.array([[1, 2, 8], [5, 8, 10]])
b = np.array([[8, 2, 1], [3, 9, 1]])
c = np.concatenate((a, b), axis = 0)
print(c)

[[ 1  2  8]
 [ 5  8 10]
 [ 8  2  1]
 [ 3  9  1]]


In [ ]:
a = np.array([[1, 2, 8], [5, 8, 10]])
b = np.array([[8, 2, 1], [3, 9, 1]])
c = np.concatenate((a, b), axis = 1)
print(c)

[[ 1  2  8  8  2  1]
 [ 5  8 10  3  9  1]]


In [ ]:
np.concatenate((a,b), axis=None) #if axis = None, then arrays are flatten before use

array([ 1,  2,  8,  5,  8, 10,  8,  2,  1,  3,  9,  1])

In [ ]:
# sorting np.sort()
arr = np.array([1,4,5,7,2])
arr

array([1, 4, 5, 7, 2])

In [ ]:
np.sort(arr)

array([1, 2, 4, 5, 7])

In [ ]:
np.sort(arr)[::-1]

array([7, 5, 4, 2, 1])

### delete elements of an array

In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.delete(arr, 1, axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

## Shape and Size of an array

`ndarray.ndim` : the number of axes \
`ndarray.size` : the total number of element \
`ndarray.shape` : the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [ ]:
my_array = np.array([[[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                          
                      [[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                         
                      [[0 ,1 ,2, 3],
                      [4, 5, 6, 7]]])

In [ ]:
my_array.shape

(3, 2, 4)

In [ ]:
my_array.size

24

In [ ]:
my_array.ndim

3

### Reshaping an array

When you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [ ]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b.shape

(2, 3)

## > Exercise 3

1. create a 3x3 matrix with values ranging from 2 to 10

2. concentenate the following arrays \
**[[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]**
![](image/lat3.png)

### Converting a 1D array into 2D array (add a new axis to an array)

You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

`np.newaxis` will increase the dimension of array by one whe it is used once. \
1D -> 2D, 2D -> 3D, and so on

In [ ]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.ndim

1

In [ ]:
# convert a 1D array to a row vector by inserting an axis along the first dimension
a2 = a[np.newaxis, :]

In [ ]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a2.ndim

2

In [ ]:
# for a column vector, you can insert an axis along the second dimension
a3 = a[:, np.newaxis]
a3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
a3.shape

(6, 1)

In [ ]:
a3.ndim

2

using `np.expand_dims`

In [ ]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
# You can use np.expand_dims to add an axis at index position 1
b = np.expand_dims(a, axis=1)
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# You can add an axis at index position 0 with
c = np.expand_dims(a, axis=0)
c

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
c.shape

(1, 6)

## Indexing and slicing

In [ ]:
from numpy import random
data = random.randint(2, 10, size=(10))
data

array([9, 6, 7, 4, 6, 7, 6, 5, 8, 7])

In [ ]:
data[3]

4

In [ ]:
data[:4]

array([9, 6, 7, 4])

In [ ]:
data[5:]

array([7, 6, 5, 8, 7])

In [ ]:
data[:-3]

array([9, 6, 7, 4, 6, 7, 6])

In [ ]:
data[-2:]

array([8, 7])

In [ ]:
data[3:6]

array([4, 6, 7])

![](image/numpy.jpg)

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

In [ ]:
a = np.array([[1 , 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.

In [ ]:
a[a<5]

array([1, 2, 3, 4])

You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.

In [ ]:
five_up = a >= 5
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


Or you can select elements that satisfy two conditions using the & and | operators:

In [ ]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
# pipe, or, vertical bar: |
five_up = (a > 5) | (a == 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1,1:3]

array([6, 7])

In [ ]:
z = np.array([[[0, 1, 3],
               [5, 7, 9]],
              
              [[0, 2, 4],
               [6, 8, 10]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9]],

       [[ 0,  2,  4],
        [ 6,  8, 10]]])

In [ ]:
z.shape

(2, 2, 3)

In [ ]:
z[0] # access row 0

array([[0, 1, 3],
       [5, 7, 9]])

In [ ]:
z[0,1] # access row 0, column 1

array([5, 7, 9])

In [ ]:
z[1,1,1:] #access row 1, column 1, depth 1-2

array([ 8, 10])

## > Exercise 4

1. create a null vector / 1D array of size 10 and update fifth value to 11.

2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
![](image/lat1.png)

4. Take a look at the following matrix. Access the [2, 1,1]

In [ ]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])


# Creating an array from existing data

You can easily use create a new array from a section of an existing array.

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

using `hstack`

In [ ]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using `hsplit`. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

In [ ]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

If you wanted to split this array into three equally shaped arrays, you would run:

In [ ]:
y = np.hsplit(x, 3)
y

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
y[2]

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])

If you want to split your array after the third and fourth column, you’d run:

In [ ]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
y = np.hsplit(x, (3,5)) #0:3, 3:5, 
y

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
y = np.hsplit(x, (1,3)) #0:1, 1:3, 
y

[array([[ 1],
        [13]]),
 array([[ 2,  3],
        [14, 15]]),
 array([[ 4,  5,  6,  7,  8,  9, 10, 11, 12],
        [16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
y = np.hsplit(x, (3,5,7)) #0:3, 3:5, 5:7,
y

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7],
        [18, 19]]),
 array([[ 8,  9, 10, 11, 12],
        [20, 21, 22, 23, 24]])]

# Basic array operations

In [ ]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [ ]:
data

array([1, 2])

In [ ]:
ones

array([1, 1])

In [ ]:
data + ones

array([2, 3])

![](image/"np_data_plus_ones.png")

In [ ]:
data - ones

array([0, 1])

In [ ]:
data * data

array([1, 4])

In [ ]:
data / data

array([1., 1.])

In [ ]:
a = np.array([1, 2, 3, 4])

a.sum()

10

sum the rows/columns

In [ ]:
b = np.array([[1, 1],
              [2, 2]])
b.sum(axis=0)

array([3, 3])

In [ ]:
b.sum(axis=1)

array([2, 4])

# Broadcasting

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with:

In [ ]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

![](image/np_multiply_broadcasting.png)

NumPy understands that the multiplication should happen with each cell. That concept is called <b> broadcasting </b>. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. 

# Working with Mathematical Formulas

The ease of implementing mathematical formulas that work on arrays is one of the things that make NumPy so widely used in the scientific Python community.

![](image/np_MSE_formula.png)

In [ ]:
n = 3
y_pred = np.array([1,1,1])
labels = np.array([1,2,3])
mse = (1/n) * np.sum(np.square(y_pred - labels))
mse

1.6666666666666665

![](image/np_mse_viz1.png)

![](image/np_mse_viz2.png)

# How to save and load NumPy objects?

The ndarray objects can be saved to and loaded from the disk files with `loadtxt` and `savetxt` functions that handle normal text files, `load` and `save` functions that handle NumPy binary files with a .npy file extension, and a `savez` function that handles NumPy files with a .npz file extension.

If you want to store a single ndarray object, store it as a .npy file using np.save. If you want to store more than one ndarray object in a single file, save it as a .npz file using `np.savez`. You can also save several arrays into a single file in compressed npz format with `savez_compressed`.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
np.save('myfile', a)

In [ ]:
# load file

b = np.load('myfile.npy')

In [ ]:
b

array([1, 2, 3, 4, 5, 6])

You can save a NumPy array as a plain text file like a .csv or .txt file with `np.savetxt`.

In [ ]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.savetxt('myfile2.csv', csv_arr)

In [ ]:
np.loadtxt('myfile2.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

# ASSIGNMENT

1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [ ]:
import pandas as pd